### ISSUE TITLE
I want it to listen 0.0.0.0:7860,what shoud i do?

### ISSUE THREAD

**Issue by KingingWang** [SWHL/LLaMADemo#1]
```
(llama) -bash-4.2$ python webapp_single.py --ckpt_dir ./../../models/7B --tokenizer_path ./../../models/tokenizer.model
Running on local URL:  http://127.0.0.1:7860
```
I want it to listen 0.0.0.0:7860,what shoud i do?

**Comment by SWHL** [comment]
- You don't have to do anything. Because the gradio has set this to default setting.
- related docs: [server_name](https://gradio.app/docs/#:~:text=browser%20console%20log-,server_name,-str%20%7C%20None)

**Comment by SWHL** [comment]
Just update the README, you can find the solution  in the [Use](https://github.com/SWHL/LLaMADemo#use)

**Comment by KingingWang** [comment]
OK,thanks
