### ISSUE TITLE
Loading a checkpoint for MP=0 but world size is 1

### ISSUE THREAD

**Issue by xuxiaoooo** [SWHL/LLaMADemo#2]
I wanna use A6000 gpu to run 65B, i just change the line 66 7B to 65B, and other code are not modified, i got this error. How can i resolve this? My DIR name are the same as README, is the error comes from the dir name difference like 'LLaMA' and 'llama_data'?

**Comment by SWHL** [comment]
Please refer the [pyllama repo](https://github.com/juncongmoo/pyllama)
The cur repo is only example for running the llama in a single gpu.
