### ISSUE TITLE
3.Run

### ISSUE THREAD

**Issue by mp075496706** [SWHL/LLaMADemo#3]
I have already followed the previous two steps, downloaded the file, and installed all the packages in the requirements.txt file.
During the third step, when executing the command "python conference.py", an error was reported, with the following information:
"ModuleNotFoundError: No module named 'hiq'"

I followed the prompts and installed the hiq package using the pip command, but still prompted the above error message.
Is it my fault to operate?

**Comment by SWHL** [comment]
Sorry, I missed the hiq package, and already update the requirement.txt.
You can try it again.

**Comment by mp075496706** [comment]
> Sorry, I missed the hiq package, and already update the requirement.txt. You can try it again.

Yes, it worked this time.
However, I still encountered the same problem as the llama project: ”ModuleNotFoundError: No module named '_ itree' “

It may be related to my use of the Windows system. I have seen this issue mentioned in the Issues of the llama project before. I will try to see if it is feasible under the Linux system.
Thank you for your timely response just now.
